### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by ajm188** [k4therin2/stockocado#1]
This would include all the packages that your library depends on

see [this](https://github.com/brenns10/slack-emojinator/blob/master/requirements.txt) as an example

**Comment by k4therin2** [comment]
Added requirements.txt (I tried using pip freeze, but that seemed like overkill, so I found this tool called pigar)

**Comment by ajm188** [comment]
Also, consider using virtualenv for more repeatable environments
